--- #YAML:1.0
name:               Crypt-RSA-Yandex
version:            0.06
abstract:           Perl binding to modified RSA library (yamrsa) for encrypting Yandex auth token
author:
    - Mons Anderson <mons@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    MIME::Base64:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
